[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_lockup = "DEQFNjLkV3sQpRsLWyR8yh7EBHJXVwvfDdjUZt4PrUuJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/com2ustaegeun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
